language: cpp

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt4-dev qt4-dev-tools

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
